# Configuration for: https://github.com/KyleKing/copier-template-tester

[ctt]
source_directory = "package_template"

[defaults]
author_email = "ctt@ctt.ctt"
author_name = "Carl The Template"
author_username = "user_ctt"
package_name_kebab = "mdformat-template-noop"
plugin_name = "template_noop"
repository_provider = "https://github.com"

[output.".ctt/default"]
