# Configuration for: https://github.com/KyleKing/copier-template-tester

[ctt]
source_directory = "package_template"

[defaults]
author_email = "executablebooks@gmail.com"
author_name = "Executable Books"
author_username = "executablebooks"
copyright_date = "2020"
plugin_name = "eb_plugin_example"
repository_provider = "https://github.com"

[output.".ctt/default"]
