[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2.0,<4"]

[project]
authors = [
  {email = "executablebooks@gmail.com", name = "Chris Sewell"},
]
classifiers = [
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
  "mdformat >=0.7.0,<0.8.0",
]
dynamic = ["description", "version"]
keywords = ["markdown", "markdown-it", "mdformat"]
name = "mdformat_plugin"
readme = "README.md"
requires-python = ">=3.7"

[project.entry-points."mdformat.parser_extension"]
plugin = "mdformat_plugin"

[project.optional-dependencies]
dev = ["pre-commit"]
test = [
  "coverage",
  "pytest-cov",
  "pytest~=6.0",
]

[project.urls]
Homepage = "https://github.com/executablebooks/mdformat-plugin"

[tool.flit.sdist]
exclude = [".github/", "tests/"]
include = []

[tool.isort]
# Force imports to be sorted by module, independent of import type
force_sort_within_sections = true
# Configure isort to work without access to site-packages
known_first_party = ["mdformat_plugin", "tests"]
# Group first party and local folder imports together
no_lines_before = ["LOCALFOLDER"]
# Settings for Black compatibility
profile = "black"
